server:
  port: 443
  log: false
  event_listeners: 15
  dev: true
security:
  token:
    salt_rounds: 12
    expiration: 2678400
    cache_ttl: 3600
    cache: true
    length: 20
  password:
    salt_rounds: 12
    max_attempts: 5
    max_history: 15
collections:
  prod:
    ip: ip
    config: config
    user: users
    token: tokens
    role: roles
    content: content
    oauth: oauth
  dev:
    ip: ip
    config: config
    user: users
    token: tokens
    role: roles
    content: content
    oauth: oauth
global_objects:
  prod:
    role: 621ce083618747546a212ddb
  dev:
    role: 621ce083618747546a212ddc
